name: pages build and deployment
on: [ workflow_dispatch, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the build
        run: sleep 2

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Do the deploy
        run: sleep 1
      - name: Telemetry
        if: always()
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --fail
