name: pages build and deployment
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the build
        run: sleep 2

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Do the deploy
        run: sleep 1

  post:
    needs: [build, deploy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Telemetry
        run: echo "telemetry here"
